routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('films.index'));
});

Route::resource('/films','Web\FilmsController');
Route::resource('/comments','Web\CommentController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Film.php
<?php

namespace App;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;

class Film extends Model
{
    use Sluggable;

    protected $table = 'films';

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }

    protected $fillable = [
        'title', 'slug', 'description', 'release_date', 'ticket_price', 'rating', 'country', 'preview'
    ];

    public function genres()
    {
        return $this->belongsToMany(Genre::class,'film_genres','film_id','genre_id');
    }

    public function comments()
    {
        return $this->hasMany(Comment::class,'film_id');
    }
}

app/Http/Controllers/Api/FilmController.php
<?php
/**
 * Created by PhpStorm.
 * User: Lakshan
 * Date: 26/09/18
 * Time: 12:35 PM
 */

namespace App\Http\Controllers\Api;


use App\Film;
use App\Genre;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Http\UploadedFile;

class FilmController extends Controller
{
    /**
     * @var Film
     */
    private $model;

    public function __construct(Film $filmModel)
    {
        $this->model = $filmModel;
    }

    /** Show list of films
     * @param Request $request
     * @return \Illuminate\Contracts\Pagination\LengthAwarePaginator
     */
    public function index(Request $request)
    {
        $items_per_page = $request->input('per_page',10);
        return $this->model->with('genres')->paginate($items_per_page);
    }

    /** Show single film by id
     * @param $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function show($id)
    {
        $film = $this->model->with('genres','comments')->find($id);

        if(!$film)
            return response()->json(['error' => 'Film not found',404]);

        return $film;
    }

    /** Saves a film
     * @param Request $request
     * @return Film
     */
    public function store(Request $request)
    {
        $validator = \Validator::make($request->all(),[
            'title' => 'required|max:255',
            'description' => 'required',
            'release_date' => 'required|date',
            'rating' => 'required|in:1,2,3,4,5',
            'ticket_price' => 'required|numeric',
            'country' => 'required',
            'preview_image' => 'required|file|image',
            'genres' => 'required|array',
            'genres.*' => 'required',
        ]);

        if($validator->fails()){
            return response()->json($validator->errors(),400);
        }

        //store uploaded file
        $preview = $request->file('preview_image');
        $stored_file_name = $this->storeUploadedFile($preview);

        // store the film
        $film_data = $request->all();
        $film_data['preview'] = "uploads/$stored_file_name";
        $film = $this->model->create($film_data);

        // attach film genres
        $genres = $this->getGenreIds($request->input('genres'));
        foreach ($genres as $genre_id) {
            $film->genres()->attach($genre_id);
        }

        return $this->model->with('genres')->find($film->id);
    }

    /** Updates a film
     * @param $id
     * @param Request $request
     * @return Film
     */
    public function update($id, Request $request)
    {
        $film = $this->model->find($id);
        if(!$film)
            return response()->json(['error' => 'Film not found',404]);

        $validator = \Validator::make($request->all(),[
            'title' => 'sometimes|max:255',
            'release_date' => 'sometimes|date',
            'rating' => 'sometimes|in:1,2,3,4,5',
            'ticket_price' => 'sometimes|numeric',
            'preview_image' => 'sometimes|file|image',
            'genres' => 'sometimes|array'
        ]);

        if($validator->fails()){
            return response()->json($validator->errors(),400);
        }

        $update_data = $request->all();

        if($request->file('preview_image') && $request->file('preview_image')->isFile())
        {
            $preview = $request->file('preview_image');
            $stored_file_name = $this->storeUploadedFile($preview);
            $update_data['preview'] = "uploads/$stored_file_name";
        }

        $film->update($update_data);

        // if genres exists to update
        if(is_array($request->input('genres'))){
            $film->genres->detach();

            $genres = $this->getGenreIds($request->input('genres'));
            foreach ($genres as $genre_id) {
                $film->genres()->attach($genre_id);
            }
        }

        return $this->model->with('genres')->find($film->id);
    }

    /** Deletes a Film
     * @param $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroy($id)
    {
        $film = $this->model->find($id);
        if(!$film)
            return response()->json(['error' => 'Film not found',404]);

        $film->delete();

        return response()->json(['message' =>'success']);
    }

    /** Find genre ids from inserted list of parses and return them
     * @param array $list
     * @return array
     */
    private function getGenreIds(array $list): array
    {
        $ids = [];

        foreach ($list as $genre_name) {
            //if genre exists get it
            $genre = Genre::where('genre',$genre_name)->first();

            if(!$genre){ // if genre not exists, create and get it
                $genre = Genre::create(['genre' => $genre_name]);
            }

            $ids[] = $genre->id;
        }

        //remove duplicates if exits
        return array_unique($ids);
    }

    /** Helper function to store uploaded image preview
     * @param UploadedFile $preview
     * @return string saved file name
     */
    private function storeUploadedFile(UploadedFile $preview): string
    {
        $original_file_name = $preview->getFilename();
        $extension = $preview->extension();
        $stored_file_name = time()."_$original_file_name.$extension";
        $preview->move(public_path('/uploads'),$stored_file_name);
        return $stored_file_name;
    }
}

app/Http/Controllers/Web/FilmsController.php
<?php
/**
 * Created by PhpStorm.
 * User: Lakshan
 * Date: 26/09/18
 * Time: 3:17 PM
 */

namespace App\Http\Controllers\Web;


use App\Film;
use App\Genre;
use App\Http\Controllers\Controller;
use GuzzleHttp\Client;
use Illuminate\Http\Request;
use Illuminate\Http\UploadedFile;

class FilmsController extends Controller
{
    /**
     * @var Film
     */
    private $model;

    public function __construct(Film $filmModel)
    {
        $this->model = $filmModel;
    }

    /** Show list of films. Data grabs from API
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function index(Request $request)
    {
        $page = $request->input('page',1);
        //get data from api
        $client = new Client(['base_uri' => 'http://localhost:8080/api']);
        $response = $client->request('GET', 'films?per_page=1&page='.$page);

        if($response->getStatusCode() != 200){
            abort("Failed to fetch data from API. Please try again.",500);
        }

        $data = json_decode($response->getBody());
        return view('films.films',compact('data'));
    }

    /** Show single film details
     * @param $slug Film slug
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show($slug)
    {
        $film = $this->model->with('genres','comments')->where('slug',$slug)->first();

        if(!$film)
            abort("Film not found",404);

        //dd($film);
        return view('films.film',compact('film'));
    }

    /** Show film creation form
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('films.create');
    }

    /** Store film data when user submit form
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        $validator = \Validator::make($request->all(),[
            'title' => 'required|max:255',
            'description' => 'required',
            'release_date' => 'required|date',
            'rating' => 'required|in:1,2,3,4,5',
            'ticket_price' => 'required|numeric',
            'country' => 'required',
            'preview_image' => 'required|image',
            'genres' => 'required',
        ]);

        if($validator->fails()){
            return redirect()->back()->withErrors($validator)->withInput();
        }

        //store uploaded file
        $preview = $request->file('preview_image');
        $stored_file_name = $this->storeUploadedFile($preview);

        // store the film
        $film_data = $request->all();
        $film_data['preview'] = "uploads/$stored_file_name";
        $film = $this->model->create($film_data);

        // attach film genres\
        $genres_vals = explode(',',$request->input('genres'));
        $genres = $this->getGenreIds($genres_vals);
        foreach ($genres as $genre_id) {
            $film->genres()->attach($genre_id);
        }

        session()->flash("Film created successfully.");

        return redirect(route('films.index'));
    }

    /** Find genre ids from inserted list of parses and return them
     * @param array $list
     * @return array
     */
    private function getGenreIds(array $list): array
    {
        $ids = [];

        foreach ($list as $genre_name) {

            $genre_name = trim($genre_name);

            //if genre exists get it
            $genre = Genre::where('genre',$genre_name)->first();

            if(!$genre){ // if genre not exists, create and get it
                $genre = Genre::create(['genre' => $genre_name]);
            }

            $ids[] = $genre->id;
        }

        //remove duplicates if exits
        return array_unique($ids);
    }

    /** Helper function to store uploaded image preview
     * @param UploadedFile $preview
     * @return string saved file name
     */
    private function storeUploadedFile(UploadedFile $preview): string
    {
        $original_file_name = $preview->getFilename();
        $extension = $preview->extension();
        $stored_file_name = time()."_$original_file_name.$extension";
        $preview->move(public_path('/uploads'),$stored_file_name);
        return $stored_file_name;
    }
}

resources/views/films/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Add Film') }}</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('films.store') }}" enctype="multipart/form-data">
                            @csrf

                            <div class="form-group row">
                                <label for="title" class="col-sm-4 col-form-label text-md-right">{{ __('Film Title') }}</label>

                                <div class="col-md-6">
                                    <input id="title" type="text" class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" name="title" value="{{ old('title') }}" required autofocus>

                                    @if ($errors->has('title'))
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="description" class="col-md-4 col-form-label text-md-right">{{ __('Description') }}</label>

                                <div class="col-md-6">
                                    <textarea id="description" name="description" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" rows="3" required>{{old('description')}}</textarea>

                                    @if ($errors->has('description'))
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="release_date" class="col-sm-4 col-form-label text-md-right">{{ __('Release Date') }}</label>

                                <div class="col-md-6">
                                    <input id="release_date" type="date" class="form-control{{ $errors->has('release_date') ? ' is-invalid' : '' }}" name="release_date" value="{{ old('release_date') }}" required>

                                    @if ($errors->has('release_date'))
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('release_date') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="rating" class="col-sm-4 col-form-label text-md-right">{{ __('Rating') }}</label>

                                <div class="col-md-6">
                                    <select name="rating" id="rating" class="form-control{{ $errors->has('rating') ? ' is-invalid' : '' }}" required>
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                        <option value="4">4</option>
                                        <option value="5">5</option>
                                    </select>

                                    @if ($errors->has('rating'))
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('rating') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="ticket_price" class="col-sm-4 col-form-label text-md-right">{{ __('Ticket Price') }}</label>

                                <div class="col-md-6">
                                    <input id="ticket_price" type="number" class="form-control{{ $errors->has('ticket_price') ? ' is-invalid' : '' }}" name="ticket_price" value="{{ old('ticket_price') }}" required>

                                    @if ($errors->has('ticket_price'))
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('ticket_price') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="country" class="col-sm-4 col-form-label text-md-right">{{ __('Country') }}</label>

                                <div class="col-md-6">
                                    <input id="country" type="text" class="form-control{{ $errors->has('country') ? ' is-invalid' : '' }}" name="country" value="{{ old('country') }}" required>

                                    @if ($errors->has('country'))
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('country') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="preview_image" class="col-sm-4 col-form-label text-md-right">{{ __('Preview Image') }}</label>

                                <div class="col-md-6">
                                    <input id="preview_image" type="file" class="form-control{{ $errors->has('preview_image') ? ' is-invalid' : '' }}" name="preview_image"  required>

                                    @if ($errors->has('preview_image'))
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('preview_image') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="genres" class="col-sm-4 col-form-label text-md-right">{{ __('Genres (Comma separated)') }}</label>

                                <div class="col-md-6">
                                    <input id="genres" type="text" class="form-control{{ $errors->has('genres') ? ' is-invalid' : '' }}" name="genres" value="{{old('genres')}}"  required>

                                    @if ($errors->has('genres'))
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('genres') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-8 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Save') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/films/film.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Film: {{$film->title}}</div>
                    <div class="card-body">
                        {{$film->description}}
                        <hr>
                        <div class="row">
                            <div class="col-md-2"><strong>Ticket Price</strong></div>
                            <div class="col-md-4">${{$film->ticket_price}}</div>
                            <div class="col-md-2"><strong>Release Date</strong></div>
                            <div class="col-md-4">{{$film->release_date}}</div>
                        </div>
                        <div class="row">
                            <div class="col-md-2"><strong>Rating</strong></div>
                            <div class="col-md-4">{{$film->rating}}/5</div>
                            <div class="col-md-2">Country</div>
                            <div class="col-md-4">{{$film->country}}</div>
                        </div>
                        <div class="row">
                            <div class="col-md-2"><strong>Genres</strong></div>
                            <div class="col-md-4">
                                @foreach($film->genres as $genre)
                                    <span class="badge badge-primary">{{$genre->genre}}</span>
                                @endforeach
                            </div>
                        </div>
                    </div>


                </div>

                <div class="card" style="margin-top: 20px">
                    <div class="card-header">Comments ({{count($film->comments)}})</div>
                    <div class="card-body">
                        @if(Auth::check())
                            <form method="POST" action="{{ route('comments.store') }}">
                                @csrf

                                <div class="form-group row">
                                    <label for="name" class="col-sm-4 col-form-label text-md-right">{{ __('Your Name') }}</label>

                                    <div class="col-md-6">
                                        <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required>

                                        @if ($errors->has('name'))
                                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="comment" class="col-md-4 col-form-label text-md-right">{{ __('Comment') }}</label>

                                    <div class="col-md-6">
                                        <textarea id="comment" name="comment" class="form-control{{ $errors->has('comment') ? ' is-invalid' : '' }}" rows="3" required></textarea>

                                        @if ($errors->has('comment'))
                                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('comment') }}</strong>
                                    </span>
                                        @endif
                                    </div>
                                </div>

                                <div class="form-group row mb-0">
                                    <div class="col-md-8 offset-md-4">
                                        <input type="hidden" name="film_id" value="{{$film->id}}">
                                        <button type="submit" class="btn btn-primary">
                                            {{ __('Add Comment') }}
                                        </button>
                                    </div>
                                </div>
                            </form>
                        @endif

                            <hr>

                            @foreach($film->comments as $comment)
                                <div class="media">
                                    <img class="mr-3" src="https://via.placeholder.com/50x50" alt="Generic placeholder image">
                                    <div class="media-body">
                                        <h5 class="mt-0">{{$comment->name}}</h5>
                                        {{$comment->comment}}
                                        <br><small>Published at: {{$comment->created_at}}</small>
                                    </div>
                                </div>
                                <hr>
                            @endforeach

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/films/films.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Films  (Total : {{$data->total}}) | Page {{$data->current_page}} of {{$data->last_page}}</div>

                    <div class="card-body">
                        <ul class="list-unstyled">
                        @foreach($data->data as $film)
                                <li class="media">
                                    <img class="mr-3" src="https://via.placeholder.com/50x50" alt="Generic placeholder image">
                                    <div class="media-body">
                                        <h5 class="mt-0 mb-1"><a href="{{route('films.show',['id'=>$film->slug])}}">{{$film->title}}</a></h5>
                                        {{$film->description}}
                                        <hr>
                                        <div class="row">
                                            <div class="col-md-2"><strong>Ticket Price</strong></div>
                                            <div class="col-md-4">${{$film->ticket_price}}</div>
                                            <div class="col-md-2"><strong>Release Date</strong></div>
                                            <div class="col-md-4">{{$film->release_date}}</div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-2"><strong>Rating</strong></div>
                                            <div class="col-md-4">{{$film->rating}}/5</div>
                                            <div class="col-md-2">Country</div>
                                            <div class="col-md-4">{{$film->country}}</div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-2"><strong>Genres</strong></div>
                                            <div class="col-md-4">
                                                @foreach($film->genres as $genre)
                                                    <span class="badge badge-primary">{{$genre->genre}}</span>
                                                @endforeach
                                            </div>
                                        </div>
                                    </div>
                                </li>
                        @endforeach
                        </ul>


                    </div>
                </div>

                <nav aria-label="Page navigation" style="margin-top: 20px">
                    <ul class="pagination">
                        @if($data->last_page_url)<li class="page-item"><a class="page-link" href="{{route('films.index')}}?page={{$data->current_page - 1}}">Previous</a></li>@endif
                        @if($data->next_page_url)<li class="page-item"><a class="page-link" href="{{route('films.index')}}?page={{$data->current_page + 1}}">Next</a></li>@endif
                    </ul>
                </nav>
            </div>
        </div>
    </div>
@endsection